name: Test PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14.17.3-buster

    container:
      image: node:${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v6

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v5
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install

      - name: Lint codebase
        run: yarn lint

      - name: Run Affected Tests
        run: yarn test
        env:
          NODE_ENV: test
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          TEST_PROFILE_ID: '350155e2-5f67-11f1-a3a8-eb2d5913f5de'
          TEST_DESTINATION_PHONE_NUMBER: '+121273631000'
